name: Endor Labs Dependency and Secrets Scan Monitoring
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  scan:
    permissions:
      security-events: write 
      contents: read 
      id-token: write 
      issues: write # Required to automatically comment on PRs for new policy violations
      pull-requests: write # Required to automatically comment on PRs for new policy violations
      actions: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Build Package
      run: npm install
    - name: Endor Labs Scan Pull Request
      uses: endorlabs/github-action@v1.1.2
      with:
        namespace: 'scott-learn'
        api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
        api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
        enable_github_action_token: false
       
